# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

hello_world <- function() {
    invisible(.Call(`_visPedigree_hello_world`))
}

#' Calculate Inbreeding and Dii using Meuwissen & Luo (1992)
cpp_calculate_inbreeding <- function(sire, dam) {
    .Call(`_visPedigree_cpp_calculate_inbreeding`, sire, dam)
}

#' Build A-Inverse Sparse Matrix Components (Henderson's Rules)
cpp_build_ainv_triplets <- function(sire, dam, dii) {
    .Call(`_visPedigree_cpp_build_ainv_triplets`, sire, dam, dii)
}

#' Calculate Additive Relationship Matrix (A) using Armadillo
cpp_calculate_A <- function(sire, dam) {
    .Call(`_visPedigree_cpp_calculate_A`, sire, dam)
}

#' Calculate Dominance Matrix (D) using Armadillo
cpp_calculate_D <- function(sire, dam, A) {
    .Call(`_visPedigree_cpp_calculate_D`, sire, dam, A)
}

#' Hadamard Product
cpp_calculate_AA <- function(A) {
    .Call(`_visPedigree_cpp_calculate_AA`, A)
}

#' Invert Dense Matrix (general purpose)
cpp_invert_dense <- function(M) {
    .Call(`_visPedigree_cpp_invert_dense`, M)
}

#' Invert Symmetric Positive-Definite Matrix (optimized)
#' Uses Cholesky decomposition, approximately 2x faster than general inversion
#' for symmetric positive-definite matrices
cpp_invert_sympd <- function(M) {
    .Call(`_visPedigree_cpp_invert_sympd`, M)
}

#' Auto-detect matrix type and use optimal inversion method
#' Checks if matrix is symmetric, then tries Cholesky (for positive-definite)
#' Falls back to general LU decomposition if Cholesky fails
cpp_invert_auto <- function(M) {
    .Call(`_visPedigree_cpp_invert_auto`, M)
}

#' Solve A*x = b using Path Logic
cpp_solve_A <- function(sire, dam, dii, b) {
    .Call(`_visPedigree_cpp_solve_A`, sire, dam, dii, b)
}

#' Generations Top-down
cpp_assign_generations_top <- function(sire, dam, topo_order) {
    .Call(`_visPedigree_cpp_assign_generations_top`, sire, dam, topo_order)
}

#' Generations Bottom-up
cpp_assign_generations_bottom <- function(sire, dam, topo_order) {
    .Call(`_visPedigree_cpp_assign_generations_bottom`, sire, dam, topo_order)
}

